name: pylops
channels:
  - defaults
  - conda-forge
  - numba
dependencies:
  - python==3.7.5
  - pip
  - numpy==1.18.4
  - scipy>=1.4.0
  - matplotlib
  - ipython
  - jupyter
  - jupytext
  - pytest
  - Sphinx
  - numpydoc
  - numba
  - icc_rt
  - pyfftw
  - pywavelets
  - pip:
    - scikit-fmm
    - spgl1
    - pytest-runner
    - setuptools_scm
    - sphinx-rtd-theme
    - sphinx-gallery
    - nbsphinx
    - image
    - segyio
